[client]
showErrorDetails = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
maxUploadSize = 50

[theme]
base = "light"
primaryColor = "#4D7C0F"
backgroundColor = "#F5F9EC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"
